---
####################################################################################
# UPDATE ENVIRONMENT'S PYTHON MODULE INSTALLATION/UPGRADE TOOLS TO LATEST VERSIONS #
####################################################################################
#
- name: Install/Upgrade Python Tools (pip, setuptools, wheel)
  ansible.builtin.pip:
    name: 
      - pip
      - setuptools
      - wheel
    state: latest
    extra_args: --upgrade
  register: pip_update_res
- name: Log Python Tools Install/Upgrade Output
  ansible.builtin.debug:
    msg: "{{pip_update_res}}"
#
####################################################
# INSTALL OS PRE-REQUISITES FOR LXML PYTHON MODULE #
####################################################
#
- name: Install FreeBSD OS Pre-requisites For LXML (libxml2, libxslt)
  community.general.pkgng:
    name: 
      - libxml2
      - libxslt
    state: latest
  register: os_pkg_install_res
- name: Log FreeBSD OS Pre-requisities Install Output
  ansible.builtin.debug:
    msg: "{{os_pkg_install_res}}"
#
###################################################################################
# INSTALL LXML (FOR PARSING/MODIFYING OPNSENSE CONFIGURATION AT /CONF/CONFIG.XML) #
###################################################################################
#
- name: Install LXML Python Module
  ansible.builtin.pip:
    name: lxml
  register: lxml_install_res
- name: Log LXML Installation Output
  ansible.builtin.debug:
    msg: "{{lxml_install_res}}" 
#
...
