---
#############################################
# MASTER HOME NETWORK CONSTRUCTION PLAYBOOK #
#############################################
#
# Start role to generate OPNSense Firewall Configuration
- name: Configure OPNSense Firewall
  connection: local
  gather_facts: true
  hosts: OPNSENSE_Instance
  roles:
    - opnsense
#
...
