---
# Set To System Interpreter (before virtual environment setup)
#
ansible_python_interpreter: /usr/bin/python3
#
# OPNSENSE Firewall Configuration Variables
#
# Hostname
opnsense_hostname: Rubidium
...
