---
#############################
# SYSTEM PYTHON INTERPRETER #
#############################
#
opnsense_system_interpreter: /usr/local/bin/python3
#
#############################################
# OPNSENSE FIREWALL CONFIGURATION VARIABLES #
#############################################
#
############
# HOSTNAME #
############
#
opnsense_hostname: GATEWAY
#
################################
# INTERNAL NETWORK DEFINITIONS #
################################
#
opnsense_roas_vlan_parent_if: "vtnet0"
#
opnsense_internal_network_defs:
  #############################
  - name: MGMT
    vlan_tag: 10
  #############################
  - name: RESTRICTED MGMT
    vlan_tag: 11
  #############################
  - name: PROXMOX BACKUP
    vlan_tag: 20
  #############################
  - name: SELF-HOSTED SERVICES
    vlan_tag: 30
  #############################
  - name: TOOLS4EVER
    vlan_tag: 40
  #############################
  - name: EXPERIMENTATION
    vlan_tag: 50
  #############################
  - name: CAMERA
    vlan_tag: 60
  #############################
  - name: IOT
    vlan_tag: 70
  #############################
  - name: FAMILY
    vlan_tag: 80
  #############################
  - name: GUEST
    vlan_tag: 90
#
...
