---
#############################
# SYSTEM PYTHON INTERPRETER #
#############################
#
opnsense_system_interpreter: /usr/local/bin/python3
#
#############################################
# OPNSENSE FIREWALL CONFIGURATION VARIABLES #
#############################################
#
############
# HOSTNAME #
############
#
opnsense_hostname: Rubidium
#
...
