---
#
####################################################
# FIREWALL CONFIGURATION TASKS ARE KICKED OFF HERE #
####################################################
#
- block:
  ############
  # HOSTNAME #
  ############
  - name: FIREWALL - CONFIGURE HOSTNAME
    ansible.builtin.include_tasks: firewall_configs/hostname.yml
  #####################
  # INTERNAL NETWORKS #
  #####################
  - name: FIREWALL - CONFIGURE INTERNAL NETWORKS
    ansible.builtin.include_tasks: ./internal_networks/internal_networks.yml
  ################
  module_defaults:
    community.general.xml:
      path: "{{control_node_config_file_path}}"
#
...