---
#
###############################
# OPNSENSE CONFIGURATION FILE #
###############################
#
config_file_path: /conf/config.xml
#
#################################
# CONFIGURATION FILE NAMESPACES #
#################################
#
ns_unbound_a_qf: "11111111-2222-3333-4444-555555555555"
ns_unbound_ptr_qf: "11111110-2222-3333-4444-555555555555"
#
...