---
#
###################################
# BUILD UNBOUND DNS CONFIGURATION #
###################################
#
#####################################################################
# ADD AN 'A' QUERY FORWARDING ENTRY (FOR HOSTNAME TO IP RESOLUTION) #
#####################################################################
#
- name: GENERATE 'A' ENTRY
  ansible.builtin.include_tasks: ./lookup_entry.yml
  vars:
    subdomain_name: '{{current_network.name | regex_replace("[\s]+", "-") | lower()}}'
    domain: "{{subdomain_name}}.internal.firstgambrellianempire.com"
    description: "{{current_network.name}} - FORWARD"
    dot_uuid: "{{ current_network.vlan_tag | to_uuid(ns_unbound_a_qf) }}"
#
######################################################################
# ADD A 'PTR' QUERY FORWARDING ENTRY (FOR IP TO HOSTNAME RESOLUTION) #
######################################################################
#
- name: GENERATE 'PTR' ENTRY
  ansible.builtin.include_tasks: ./lookup_entry.yml
  vars:
    domain: "{{current_network.vlan_tag}}.19.10.in-addr.arpa"
    description: "{{current_network.name}} - REVERSE"
    dot_uuid: "{{ current_network.vlan_tag | to_uuid(ns_unbound_ptr_qf) }}"
#
...