---
#
##############################
# INITIAL CONFIGURATION PREP #
##############################
#
- name: PREP FOR CONFIGURATION BUILD
  ansible.builtin.include_tasks: initial_prep/configure.yml
#
############################################
# GENERATE OPNSENSE FIREWALL CONFIGURATION #
############################################
#
- name: BUILD FIREWALL CONFIGURATION FILE
  ansible.builtin.include_tasks: xml_configs/configure.yml
#
################################
# RUN POST-CONFIGURATION TASKS #
################################
#
- name: RUN POST-CONFIGURATION TASKS
  ansible.builtin.include_tasks: post_config_actions/configure.yml
#
...