---
#
####################################################
# SETTING UP PRE-REQUISITES ON UBUNTU CONTROL NODE #
####################################################
#
- block:
  - name: CONTROL NODE - INSTALL PRE-REQUISITE OS PACKAGES
    ansible.builtin.include_tasks: control_node_prep.yml
  become: true
  become_user: root
  become_method: ansible.builtin.sudo
#
###################################
# PREPARE FOR CONFIGURATION BUILD #
###################################
#
- name: FIREWALL - DOWNLOADING EXISTING CONFIGURATION FILE
  ansible.builtin.include_tasks: config_file_prep.yml
#
############################################
# GENERATE OPNSENSE FIREWALL CONFIGURATION #
############################################
#
- name: FIREWALL - BUILD CONFIGURATION
  ansible.builtin.include_tasks: firewall_configs/configure.yml
#
###################
# REBOOT FIREWALL #
###################
#
#- name: Reboot Firewall
#  ansible.builtin.reboot:
#    msg: Rebooting to cement Ansible configuration...
#  vars: 
#    ansible_python_interpreter: "/usr/local/bin/python3"
#
...