---
#
####################################################
# SETTING UP PRE-REQUISITES ON UBUNTU CONTROL NODE #
####################################################
#
- block:
  - name: CONTROL NODE - Installing Pre-Requisite OS Packages
    ansible.builtin.include_tasks: control_node_prep.yml
  become: true
  become_user: root
  become_method: ansible.builtin.sudo
#
#################################################
# PULL DOWN COPY OF EXISTING CONFIGURATION FILE #
#################################################
#
- name: Pull OPNSense Configuration File At [{{config_file_path}}]
  ansible.builtin.fetch:
    src: "{{config_file_path}}"
    dest: "{{ansible_env.HOME}}/ansible/opnsense-config"
  connection: paramiko
  become: false
  vars: 
    ansible_python_interpreter: "{{opnsense_system_interpreter}}"
#
############################################
# GENERATE OPNSENSE FIREWALL CONFIGURATION #
############################################
# Set Hostname
#- name: CONFIG - HOSTNAME
#  ansible.builtin.include_tasks: config/hostname.yml
#  module_defaults:
#    community.general.xml:
#      path: "{{config_file_path}}"
#
###################
# REBOOT FIREWALL #
###################
#
#- name: Reboot Firewall
#  ansible.builtin.reboot:
#    msg: Rebooting to cement Ansible configuration...
#  vars: 
#    ansible_python_interpreter: "/usr/local/bin/python3"
#
...