---
#
##############################
# INITIAL CONFIGURATION PREP #
##############################
#
- name: PREP FOR CONFIGURATION BUILD
  ansible.builtin.include_tasks: initial_prep/configure.yml
#
############################################
# GENERATE OPNSENSE FIREWALL CONFIGURATION #
############################################
#
- name: BUILD FIREWALL CONFIGURATION FILE
  ansible.builtin.include_tasks: xml_configs/configure.yml
#
###################
# REBOOT FIREWALL #
###################
#
#- name: Reboot Firewall
#  ansible.builtin.reboot:
#    msg: Rebooting to cement Ansible configuration...
#  vars: 
#    ansible_python_interpreter: "/usr/local/bin/python3"
#
...