---
#
####################################################
# SETTING UP PRE-REQUISITES ON UBUNTU CONTROL NODE #
####################################################
#
- block:
  - name: Installing Pre-Requisite OS Packages On Ubuntu Control Node
    ansible.builtin.include_tasks: pre_requisites/control_node.yml
  become: true
  become_user: root
  become_method: ansible.builtin.sudo
#
#################################################
# PULL OPNSENSE MANAGED NODE CONFIGURATION FILE #
#################################################
#
- block:
  - name: Pulling OPNSense Managed Node Configuration File
    ansible.builtin.include_tasks: pre_requisites/config_pull.yml
  connection: paramiko
  become: false
  vars: 
    ansible_python_interpreter: "{{opnsense_system_interpreter}}"
#
############################################
# GENERATE OPNSENSE FIREWALL CONFIGURATION #
############################################
# Set Hostname
#- name: CONFIG - HOSTNAME
#  ansible.builtin.include_tasks: config/hostname.yml
#  module_defaults:
#    community.general.xml:
#      path: "{{config_file_path}}"
#
###################
# REBOOT FIREWALL #
###################
#
#- name: Reboot Firewall
#  ansible.builtin.reboot:
#    msg: Rebooting to cement Ansible configuration...
#  vars: 
#    ansible_python_interpreter: "/usr/local/bin/python3"
#
...